// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJoQ0YsI1uFbk-vRVD_b8PoAntHas5n5w',
    appId: '1:505278602349:web:9141e92aa8484ce80bf364',
    messagingSenderId: '505278602349',
    projectId: 'push-notifications-9ed52',
    authDomain: 'push-notifications-9ed52.firebaseapp.com',
    storageBucket: 'push-notifications-9ed52.appspot.com',
    measurementId: 'G-ZBE3R6JJG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeLM2xpOZEsF4uZkkXhf3leEKY4S-AjBQ',
    appId: '1:505278602349:android:3ef3387b5fc7105b0bf364',
    messagingSenderId: '505278602349',
    projectId: 'push-notifications-9ed52',
    storageBucket: 'push-notifications-9ed52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVOnYNN8-DZpAW2wj8iJSez57gYKqsgGA',
    appId: '1:505278602349:ios:3a34cf076e8984760bf364',
    messagingSenderId: '505278602349',
    projectId: 'push-notifications-9ed52',
    storageBucket: 'push-notifications-9ed52.appspot.com',
    iosBundleId: 'com.example.testNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVOnYNN8-DZpAW2wj8iJSez57gYKqsgGA',
    appId: '1:505278602349:ios:3a34cf076e8984760bf364',
    messagingSenderId: '505278602349',
    projectId: 'push-notifications-9ed52',
    storageBucket: 'push-notifications-9ed52.appspot.com',
    iosBundleId: 'com.example.testNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJoQ0YsI1uFbk-vRVD_b8PoAntHas5n5w',
    appId: '1:505278602349:web:8d99d3e9fe4a8bdd0bf364',
    messagingSenderId: '505278602349',
    projectId: 'push-notifications-9ed52',
    authDomain: 'push-notifications-9ed52.firebaseapp.com',
    storageBucket: 'push-notifications-9ed52.appspot.com',
    measurementId: 'G-02TCFBWKS4',
  );
}
